apiVersion: apps/v1
kind: Deployment
metadata:
  name: bottles-dep-v1
  labels:
    app: bottles
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bottles
      version: v1
  template:
    metadata:
      labels:
        app: bottles
        version: v1
    spec:
      containers:
      - name: bottles
        image: meshery20/bottle-producer:1.1.0
        ports:
        - containerPort: 3002
        env:
        - name: SERVER_PORT
          value: "3002"
        - name: BASE_PRODUCTION_TIME_MS
          value: "15"
        - name: MAX_PRODUCTION_DELAY_MS
          value: "50"
        - name: PRODUCTION_FAIL_PROBABILITY
          value: "0.05"
        imagePullPolicy: Always


